artofcooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipeblog.urls'), name='recipe_urls'),
    path('accounts/', include('allauth.urls')),
]

recipeblog/urls.py
from . import views
from django.urls import path


urlpatterns = [
     path('', views.PostRecipe.as_view(), name='home'),
     path('view_recipe/<slug:slug>/', views.RecipeDetail.as_view(),
          name='view_recipe'),
     path('like/<slug:slug>', views.LikeRecipe.as_view(), name='like_recipe'),
     path('share_recipe/', views.ShareRecipe.as_view(), name='share_recipe'),
     path('user_recipe/', views.UserRecipes.as_view(), name='user_recipes'),
     path('edit_recipe/<slug:slug>', views.EditRecipe.as_view(),
          name='edit_recipe'),
     path('delete_recipe/<int:pk>', views.DeleteRecipe.as_view(),
          name='delete_recipe'),
     path('saved_recipe/', views.SavedRecipe.as_view(), name='saved')
]

recipeblog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
import cloudinary.uploader
from django.urls import reverse
from django.utils.text import slugify

STATUS = ((0, "Draft"), (1, "Published"))


class Recipe(models.Model):

    CATEGORIES = [
        ("Breakfast", "Breakfast"),
        ("Lunch", "Lunch"),
        ("Dinner", "Dinner"),
        ("Appetizer", "Appetizer"),
        ("Salad", "Salad"),
        ("Baked-goods", "Baked-goods"),
        ("Dessert", "Dessert"),
        ("Soup", "Soup"),
        ("Vegetarian", "Vegetarian")
    ]

    title = models.CharField(max_length=100)
    slug = models.SlugField(
        max_length=200, unique=True, null=False)
    featured_image = CloudinaryField('Main Image', default='placeholder')
    excerpt = models.TextField(max_length=150)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posted_recipes')
    category = models.CharField(max_length=100, choices=CATEGORIES)
    servings = models.PositiveIntegerField()
    ingredients = models.TextField()
    direction = models.TextField()
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='recipe_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return '{} {} {}'.format(self.title, self.category, self.author)

    def number_of_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(f"{self.title}-{self.category}-{str(self.author)}")
        super(Recipe, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('user_recipes')


class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

recipeblog/forms.py
from .models import Comment, Recipe
from django import forms
from django.forms import ModelForm, TextInput
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class RecipeForm(forms.ModelForm):

    class Meta:
        model = Recipe

        widgets = {
            'direction': SummernoteWidget(),
            'ingredients': SummernoteWidget(),
            'excerpt': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 400px;',
                'placeholder': 'Enter a short description of your recipe'
                }),
            'author': TextInput(attrs={'id': 'username', 'type': 'hidden'}),
        }

        fields = [
            'title',
            'excerpt',
            'author',
            'featured_image',
            'category',
            'servings',
            'ingredients',
            'direction',
            'status',
        ]

recipeblog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views.generic import ListView, View, CreateView, UpdateView
from django.http import HttpResponseRedirect
from .models import Recipe, Comment
from .forms import CommentForm, RecipeForm


class PostRecipe(ListView):
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


class RecipeDetail(View):

    def get(self, request, slug, *args, **kwargs):
        """
        Get method for fetching comments and post details and returning
        variables.
        """
        queryset = Recipe.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = post.comments.filter(approved=True).order_by('created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "view_recipe.html",
            {
                "recipe": post,
                "comments": comment,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):
        """
        Post method for comment form setting recipe object and returning
        variables.
        """

        queryset = Recipe.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by('created_on')
        liked = False

        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "view_recipe.html",
            {
                "recipe": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )


class LikeRecipe(View):

    def post(self, request, slug, *args, **kwargs):
        post = get_object_or_404(Recipe, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('view_recipe', args=[slug]))


class ShareRecipe(CreateView):

    model = Recipe
    form_class = RecipeForm
    template_name = 'share_recipe.html'


class UserRecipes(ListView):

    model = Recipe
    template_name = 'user_recipes.html'

    def get(self, request):

        queryset = Recipe.objects.filter(
            author=request.user.id).order_by('-created_on')
        queryset_dict = {
            'your_recipes': queryset,
        }

        return render(
            request,
            self.template_name,
            queryset_dict,
        )


class EditRecipe(UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'edit_recipe.html'


class DeleteRecipe(View):

    def get(self, request, pk, *args, **kwargs):

        recipe = get_object_or_404(Recipe, pk=pk)
        recipe.delete()

        return redirect(reverse('user_recipes'))


class SavedRecipe(ListView):

    model = Recipe
    template_name = 'saved_recipe.html'

    def get(self, request):

        author = request.user
        queryset = Recipe.objects.filter(status=1).filter(likes=author)
        queryset_dict = {
            'saved_recipes': queryset,
        }

        return render(
            request,
            self.template_name,
            queryset_dict,
        )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@1,300&amp;family=Playfair+Display&amp;display=swap"
        rel="stylesheet">
    <!-- Static CSS File -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Title -->
    <title>The Art of Cooking</title>
</head>

<body class="d-flex flex-column main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <h1>The Art Of Cooking</h1>
            </a>
            <button class="navbar-toggler hamburger" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon hamburger"></span>
            </button>
            <div class="collapse navbar-collapse nav-options" id="navbarText">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'user_recipes' %}">View Your Own
                            Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'saved' %}">Saved
                            Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-btn btn" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3">
        <p class="m-0 text-center">Made by Fatima Qaiser</p>
        <p class="m-0 text-center">Follow on: <a href="https://github.com/fatimaqais" class="nav-btn" target="_blank"><i
                    class="fab fa-github"></i></a>
            <a href="https://www.linkedin.com/in/fatima-qaiser/" class="nav-btn" target="_blank"><i
                    class="fab fa-linkedin"></i></a></p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/edit_recipe.html
{% extends "base.html" %} {% block content %}

<!-- Cloudinary -->
{% load cloudinary %}

<!-- Crispy Forms -->
{% load crispy_forms_tags %}

<div class="col-md-12 hero-image hero-container">
    <section class="text-center">
        <h2 class="hero-text">Create your Own Recipe Now!</h2>
        <hr class="block-divider">
        <p class="lead">
            <strong><mark>Finish Your Drafts or Create New Post</mark></strong></p>
        <div class="hero-options">
            <a class="nav-link btn btn-background" href="{% url 'user_recipes' %}">View your Recipes</a>
        </div>
    </section>
</div>

<div class="container justify-content-around">
    <div class="create-post" id="recipe-form">
        <!-- edit recipe form -->
        <form method="POST" enctype="multipart/form-data">
            <h2 class="text-center">Edit Your Recipe</h2>
            <div class="text-center">
                {% csrf_token %}
                <p class="recipe-form">Title: {{ form.title }}</p>
                <p class="recipe-form">Excerpt: {{ form.excerpt }}</p>
                <div>
                    <p>Upload an image: {{ form.featured_image }}</p>
                </div>
                <div>
                    <p>Ingredients:</p>
                    {{ form.ingredients }}
                </div>
                <div>
                    <p>Directions:</p>
                    {{ form.direction }}
                </div>
                <div>
                    <div>
                        <p> Servings: {{ form.servings }}</p>
                    </div>
                    <div>
                        <p>Category: {{ form.category }}</p>
                    </div>
                    <div>
                        {{ form.author }}
                    </div>
                    <div>
                        <p>Status: {{ form.status }}</p>
                    </div>
                </div>
                <button id="submit-recipe" class="btn post-btn" type="submit">Share</button>
            </div>
        </form>
    </div>
</div>
<!-- display a thank you message once form is submitted -->
<div class="container text-center">
    <div id="thank-you" class="hidden">
        <div class="thanks">
            <h2 class="card-title">Thankyou for sharing that amazing recipe!</h2>
            <div class="image-container">
                <img class="card-img-top card-img"
                    src="https://res.cloudinary.com/dnisemsbn/image/upload/v1685371870/happy-food_stlv2v.jpg"
                    alt="happy dog image printed on a toast">
            </div>
            <muted>You will be redirected to your recipe page in few minutes</muted>
        </div>
    </div>
</div>

<script>
    var author = '{{ user.username }}';
    document.getElementById("username").placeholder = author;
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-12 hero-image hero-container">
    <section class="text-center">
        <h2 class="hero-text">Check out the latest most delicious recipes today!</h2>
        <hr class="block-divider">
        {% if user.is_authenticated %}
        <p class="lead">
            <strong><mark>Share your own Recipes Now!</mark></strong></p>
        <div class="hero-options">
            <a class="nav-link btn btn-background" href="{% url 'user_recipes' %}">View your Recipes</a>
            <a class="nav-link btn btn-background" href="{% url 'share_recipe' %}">Create New Recipe</a>
        </div>
        {% else %}
        <p class="lead">
            <strong><mark>Sign Up Now to share your own Recipes!</mark></strong></p>
        <div class="hero-options">
            <a class="nav-link btn btn-background" href="{% url 'account_signup' %}">Sign Up</a>
            <a class="nav-link btn btn-background" href="{% url 'account_login' %}">Login</a>
        </div>
        {% endif %}
    </section>
</div>

<div class="container-fluid recipe-section">
    <div class="text-center">
        <h2>Recipes</h2>
        <p>View all the shared recipes by people!</p>
    </div>

    <!-- Recipe Card -->
    <div class="justify-content-around">
        <div class="col-12">
            <!-- recipe post -->
            <div class="row">
                {% for post in recipe_list %}
                <div class="card-space col-md-4">
                    <div class="card card-body">
                        <div class="text-center">
                            <h3 class="card-title">{{ post.title }}</h3>
                        </div>
                        <div class="image-container">
                            {% if "placeholder" in post.featured_image.url %}
                            <img class="card-img-top card-img"
                                src="https://res.cloudinary.com/dnisemsbn/image/upload/v1684097187/all-food_pua55k.jpg"
                                alt="image of ingredients">
                            {% else %}
                            <img class="card-img-top card-img" src=" {{ post.featured_image.url }}"
                                alt="Pictures of prepared food dishes">
                            {% endif %}
                        </div>
                        <div class="text-center">
                            <p class="card-text">{{ post.excerpt }}</p>
                        </div>
                        <div class="text-center card-body">
                            <a href="{% url 'view_recipe' post.slug %}" class="btn post-btn">View Full Recipe</a>
                        </div>
                        <div class="card-body">
                            <div class="text-center">
                                <p><i class="far fa-heart"></i> {{ post.number_of_likes }}</p>
                                {% if user.is_authenticated %}
                                <p>Like this post to show your appreciation and save it in your collections</p>
                                {% else %}
                                <p>Sign up or Login now to like this recipe and save it it in your collection!</p>
                                {% endif %}
                            </div>
                            <hr>
                            <p class="card-text text-muted h5 text-center">{{ post.created_on}}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <div>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="nav-link btn btn-background">&laquo; PREV
                </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="nav-link btn btn-background">
                    NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </div>
    {% endif %}
</div>

{% endblock %}

templates/saved_recipe.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-12 hero-image hero-container">
    <section class="text-center">
        <h2 class="hero-text">View All The Recipes Liked By You!</h2>
        <hr class="block-divider">
        <p class="lead">
            <strong><mark>Share your own Recipes Now!</mark></strong></p>
        <div class="hero-options">
            <a class="nav-link btn btn-background" href="{% url 'user_recipes' %}">View your Recipes</a>
            <a class="nav-link btn btn-background" href="{% url 'share_recipe' %}">Create New Recipe</a>
        </div>
    </section>
</div>

<div class="container-fluid recipe-section">
    <div class="text-center">
        <h2>Your Liked Recipes</h2>
        <p>View all the shared recipes by people!</p>
    </div>

    <!-- Recipe Card -->
    <div class="row justify-content-around">
        <div class="col-12">
            <!-- recipe post -->
            <div class="row">
                {% for recipe in saved_recipes %}
                <div class="card-space col-md-4">
                    <div class="card card-body">
                        <div class="text-center">
                            <h3 class="card-title">{{ recipe.title }}</h3>
                        </div>
                        <div class="image-container">
                            {% if "placeholder" in recipe.featured_image.url %}
                            <img class="card-img-top card-img"
                                src="https://res.cloudinary.com/dnisemsbn/image/upload/v1684097187/all-food_pua55k.jpg"
                                alt="image of ingredients">
                            {% else %}
                            <img class="card-img-top card-img" src=" {{ recipe.featured_image.url }}"
                                alt="Pictures of prepared food dishes">
                            {% endif %}
                        </div>
                        <div class="text-center">
                            <p class="card-text">{{ recipe.excerpt }}</p>
                        </div>
                        <div class="text-center card-body">
                            <a href="{% url 'view_recipe' recipe.slug %}" class="btn post-btn">View Full Recipe</a>
                        </div>
                        <div class="card-body">
                            <div class="text-center">
                                <p><button type="submit" name="recipe_id" value="{{recipe.slug}}" class="btn-like"><i
                                            class="fas fa-heart"></i></button> {{ recipe.number_of_likes }}</p>
                            </div>
                            <hr />
                            <p class="card-text text-muted h5 text-center">{{ recipe.created_on}}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/share_recipe.html
{% extends "base.html" %} {% block content %}

<!-- Cloudinary -->
{% load cloudinary %}

<!-- Crispy Forms -->
{% load crispy_forms_tags %}

<div class="col-md-12 hero-image hero-container">
    <section class="text-center">
        <h2 class="hero-text">Create your Own Recipe Now!</h2>
        <hr class="block-divider">
        <p class="lead">
            <strong><mark>Finish Your Drafts or Create New Post</mark></strong></p>
        <div class="hero-options">
            <a class="nav-link btn btn-background" href="{% url 'user_recipes' %}">View your Recipes</a>
        </div>
    </section>
</div>

<div class="container justify-content-around">
    <h2 class="text-center">Create a New Recipe Post</h2>
    <div class="create-post" id="recipe-form">
        <!-- share recipe form for user to create new recipe-->
        <form method="POST" enctype="multipart/form-data">
            <div class="text-center">
                {% csrf_token %}
                <p class="recipe-form">Title: {{ form.title }}</p>
                <p class="recipe-form">Excerpt: {{ form.excerpt }}</p>
                <div>
                    <p>Upload an image: {{ form.featured_image }}</p>
                </div>
                <div>
                    <p>Ingredients:</p>
                    {{ form.ingredients }}
                </div>
                <div>
                    <p>Directions:</p>
                    {{ form.direction }}
                </div>
                <div>
                    <div>
                        {{ form.author }}
                    </div>
                    <div>
                        <p> Servings: {{ form.servings }}</p>
                    </div>
                    <div>
                        <p>Category: {{ form.category }}</p>
                    </div>
                    <div>
                        <p>Status: {{ form.status }}</p>
                    </div>
                </div>
                <button id="submit-recipe" class="btn post-btn" type="submit">Share</button>
            </div>
        </form>
    </div>
</div>
<div class="container text-center">
    <div id="thank-you" class="hidden">
        <div class="thanks">
            <h2 class="card-title">Thankyou for sharing that amazing recipe!</h2>
            <div class="image-container">
                <img class="card-img-top card-img"
                    src="https://res.cloudinary.com/dnisemsbn/image/upload/v1685371870/happy-food_stlv2v.jpg"
                    alt="happy dog image printed on a toast">
            </div>
            <muted>You will be redirected to your recipe page in few minutes</muted>
        </div>
    </div>
</div>

<script>
    var author = '{{ user.id }}';
    document.getElementById("username").value = author;
</script>

{% endblock %}

templates/view_recipe.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<style>
    body {
        background-image: url('https://res.cloudinary.com/dnisemsbn/image/upload/q_38/v1684022232/background-food_vfebbs.jpg');
        background-attachment: fixed;
        background-size: auto;
        background-repeat: round;
    }
</style>

<div class="container recipe-page">
    <div class="row justify-content-around">
        <div class="col-md-6">
            <div class="text-center">
                <h2>{{ recipe.title }}</h2>
                <hr class="block-divider">
                <p>{{ recipe.author }} | {{ recipe.created_on}}</p>
                <p>{{ recipe.excerpt }}</p>
                <p>Serves: {{ recipe.servings }} people</p>
            </div>
            <div>
                <div class="like-comments">
                    <div><strong>{% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'like_recipe' recipe.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="recipe_id" value="{{recipe.slug}}" class="btn-like"><i
                                        class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="recipe_id" value="{{recipe.slug}}" class="btn-like"><i
                                        class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %} {{ recipe.number_of_likes }}</strong></div>
                    {% with comments.count as total_comments %}
                    <div><strong><i class="far fa-comments"></i> {{ total_comments }}</strong></div>
                    {% endwith %}
                </div>
                <p class="text-center">Like this post to save it you favourite recipes now!</p>
            </div>
        </div>
        <!-- if no image is uploaded by user, display placeholder image -->
        <div class="col-md-6 view-img">
            <div class="card-img">
                {% if "placeholder" in recipe.featured_image.url %}
                <img src="https://res.cloudinary.com/dnisemsbn/image/upload/v1684097187/all-food_pua55k.jpg"
                    width="100%">
                {% else %}
                <img src="{{ recipe.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
    <!-- displays the recipe without html tags -->
    <div class="row justify-content-around">
            <div class="col-md-4 content">
                <h3>
                    Ingredients:
                </h3>
                <p>{{ recipe.ingredients|safe }}</p>
            </div>
            <div class="col-md-8 content">
                <h3>Method:</h3>
                <p>{{ recipe.direction|safe }}</p>
        </div>
        <!-- add comment section -->
        <div class="row">
            <div class="col-md-8">
                <div class="comment-box">
                    <h3 class="sticky-sm-top">Comments:</h3>
                    {% for comment in comments %}
                    <div>
                        <strong>{{ comment.name }}</strong>
                        <p>{{ comment.body }}</p>
                        <span class="text-muted">{{ comment.created_on}}</span>
                        <hr>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 post-comment">
                <div>
                    {% if commented %}
                    <div class="alert alert-success" role="alert">
                        Your comment is awaiting approval
                    </div>
                    {% else %}
                    {% if user.is_authenticated %}

                    <h3>Leave a comment:</h3>
                    <p>Posting as: {{ user.username }}</p>
                    <form method="post" style="margin-top: 1.3em;">
                        {{ comment_form | crispy }}
                        {% csrf_token %}
                        <br>
                        <button type="submit" class="btn btn-signup post-btn btn-lg">Submit</button>
                    </form>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="conatiner back-btn">
    <a href="{% url 'home' %}" class="btn post-btn">Go Back to Home Page</a>
</div>

{% endblock %}